-- AceDecks: apply 2026-09-18
--
-- Two migrations, in the order they must run. Generated by
-- scripts/build-sql-bundle-2026-09-18.mjs from supabase/migrations/ -- edit
-- those, not this.
--
-- 01  PRIVACY. Closes read access that let anyone holding the public anon
--     key download every student's notes and mistakes, and stops a student
--     from setting their own plan to Pro. Apply this first, and soon.
-- 02  STUDY SIGNALS. Why-wrong notes on questions, real flashcards with
--     per-student review state, confidence on answers, the onboarding
--     profile columns, and the mistake-explanation cache. The app runs
--     without it (every new column is read with a fallback), but flashcards,
--     confidence tracking and onboarding only persist once it is applied.
--
-- Every statement is idempotent: running this twice is safe, and so is
-- re-running it after applying part of it. Every statement was parsed with
-- PostgreSQL's own grammar (libpg_query) before this file was generated.

-- ======================================================================
-- PREFLIGHT
-- ======================================================================

do $$
begin
  if to_regclass('public.decks') is null or to_regclass('public.matches') is null then
    raise exception 'AceDecks: core tables are missing.'
      using hint = 'This database is not an AceDecks database, or the early migrations were never applied.';
  end if;

  if to_regclass('public.classroom_rooms') is null then
    raise exception 'AceDecks: table public.classroom_rooms is missing.'
      using hint = 'Apply supabase/migrations/20260709_growth_foundations.sql first.';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'decks' and column_name = 'is_public'
  ) then
    raise exception 'AceDecks: decks.is_public is missing.'
      using hint = 'Apply supabase/migrations/20260831_public_deck_sharing.sql first.';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'roasts_enabled'
  ) then
    raise exception 'AceDecks: profiles.roasts_enabled is missing.'
      using hint = 'Apply supabase/migrations/20260802_roast_preferences.sql first.';
  end if;
end
$$;


-- ======================================================================
-- FILE: 20260918_01_privacy_lockdown.sql
-- ======================================================================

-- Close the two holes that let one account read or rewrite another's data.
--
-- 1. Every student's notes were public.
--
--    20260711_core_tables_rls_hardening.sql gave decks, questions, matches,
--    match_answers and mistake_breakdowns a SELECT policy of `using (true)`
--    for anon and authenticated, so that challenge links, tournaments and
--    ghost replays could read a deck "by reference". The anon key ships in
--    every page bundle, so `using (true)` is not "by reference", it is
--    "to anyone": one REST call returned every deck's raw_notes and
--    student_name, and every student's wrong answers and misconceptions.
--
--    A deck is now readable only when there is a reason for this caller to
--    read it: they own it, its owner published it, it has a live challenge
--    link, or it is a classroom room's deck. Questions, matches, answers and
--    breakdowns inherit that, so nothing a student never shared is visible
--    to anyone but them. Every flow that legitimately reads another
--    student's deck (a challenge, a tournament, a published set, a ghost
--    replay on a shared deck) sits inside one of those four reasons.
--
-- 2. A student could make themselves Pro.
--
--    profiles_update_own let a signed-in user update ANY column of their own
--    row, including `plan` and `stripe_customer_id`. The same migration
--    noted it and recommended a trigger that was never written. One
--    browser-console call set plan = 'founder'; pointing
--    stripe_customer_id at somebody else's customer opened THEIR billing
--    portal. Column-level grants fix it at the source: the browser may
--    update the handful of preference columns and nothing else. The service
--    role (checkout webhook, admin) is unaffected.
--
-- Safe to run more than once.

-- ---------------------------------------------------------------- helper

-- SECURITY DEFINER so it can see matches.share_token and classroom_rooms,
-- which the calling role cannot read directly. It answers one yes/no
-- question and returns no row data, so running with elevated rights leaks
-- nothing beyond "this deck is shared".
create or replace function public.deck_is_readable(p_deck_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1 from public.decks d
      where d.id = p_deck_id
        and (
          (d.user_id is not null and d.user_id = auth.uid())
          or coalesce(d.is_public, false)
        )
    )
    or exists (
      select 1 from public.matches m
      where m.deck_id = p_deck_id
        and m.share_token is not null
        and (m.share_token_expires_at is null or m.share_token_expires_at > now())
    )
    or exists (
      select 1 from public.classroom_rooms r
      where r.deck_id = p_deck_id
    );
$$;

revoke all on function public.deck_is_readable(uuid) from public;
grant execute on function public.deck_is_readable(uuid) to anon, authenticated;

-- The challenge clause is the hot path inside the policy; keep it an index
-- probe rather than a scan of every match on the deck.
create index if not exists matches_deck_shared_idx
  on public.matches (deck_id)
  where share_token is not null;

-- ---------------------------------------------------------------- decks

drop policy if exists "decks_read" on public.decks;
create policy "decks_read"
  on public.decks
  for select
  to anon, authenticated
  using (public.deck_is_readable(id));

-- ------------------------------------------------------------ questions

drop policy if exists "questions_read" on public.questions;
create policy "questions_read"
  on public.questions
  for select
  to anon, authenticated
  using (public.deck_is_readable(deck_id));

-- -------------------------------------------------------------- matches

-- Your own sessions always; anyone else's only on a deck you can see
-- (leaderboards and ghost replays exist only on shared decks).
drop policy if exists "matches_read" on public.matches;
create policy "matches_read"
  on public.matches
  for select
  to anon, authenticated
  using (
    (user_id is not null and user_id = auth.uid())
    or public.deck_is_readable(deck_id)
  );

-- --------------------------------------------------------- match_answers

-- Evaluated as the caller, so this is exactly "the match is visible to me".
drop policy if exists "match_answers_read" on public.match_answers;
create policy "match_answers_read"
  on public.match_answers
  for select
  to anon, authenticated
  using (
    exists (select 1 from public.matches m where m.id = match_answers.match_id)
  );

-- ---------------------------------------------------- mistake_breakdowns

drop policy if exists "mistake_breakdowns_read" on public.mistake_breakdowns;
create policy "mistake_breakdowns_read"
  on public.mistake_breakdowns
  for select
  to anon, authenticated
  using (
    exists (select 1 from public.matches m where m.id = mistake_breakdowns.match_id)
  );

-- -------------------------------------------------------------- profiles

-- Row policy stays "your own row"; the grant now says which columns.
revoke update on public.profiles from anon, authenticated;
grant update (display_name, roasts_enabled) on public.profiles to authenticated;


-- ======================================================================
-- FILE: 20260918_02_study_signals.sql
-- ======================================================================

-- The signals the study loop was missing, and real flashcards.
--
-- 1. questions.choice_feedback
--    Why each wrong option is wrong, keyed by the option's text. Written by
--    the question writer at generation time, so the moment a student picks
--    a wrong option they see why THAT option is wrong -- instantly, with no
--    model call, and specific to what they actually chose.
--
-- 2. flashcards / flashcard_state
--    The Flashcards tab used to show each multiple-choice stem as a card
--    ("Which of the following...?" with the options stripped), and kept the
--    student's ratings in localStorage, where they never reached mastery,
--    never scheduled a review, and vanished on another device. Cards are now
--    written as cards, and review state lives per student on the server.
--    Content and state are separate tables because a published deck's cards
--    are readable by anyone with the link, and a student's lapses are not.
--
-- 3. match_answers.confidence, topic_review_schedule.confident_misses
--    How sure the student was before they saw the answer. A confident wrong
--    answer is a misconception -- the most important thing to fix and the
--    least likely to fix itself -- and until now it looked exactly like a
--    guess.
--
-- 4. profiles learning columns
--    What the student is studying for and by when, collected in onboarding
--    and used to decide what Home recommends. Written only through
--    /api/profile/learning (service role); the browser's column grants
--    from 20260918_01 are deliberately not widened.
--
-- Safe to run more than once. Requires 20260918_01_privacy_lockdown.sql
-- (for public.deck_is_readable).

-- ------------------------------------------------------ choice feedback

alter table if exists public.questions
  add column if not exists choice_feedback jsonb;

comment on column public.questions.choice_feedback is
  'Map of wrong-option text to one sentence on why it is wrong. Written at generation time.';

-- ----------------------------------------------------------- flashcards

create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  deck_id uuid not null references public.decks(id) on delete cascade,
  front text not null,
  back text not null,
  note text,
  topic text not null default 'General',
  kind text not null default 'concept'
    check (kind in ('definition', 'concept', 'application', 'reverse')),
  position integer not null default 0,
  created_at timestamptz not null default now()
);

-- Unique, not just indexed: two tabs opening an older set at the same moment
-- both write its cards, and the second insert must fail rather than double
-- the deck.
create unique index if not exists flashcards_deck_position_key
  on public.flashcards (deck_id, position);

alter table public.flashcards enable row level security;

-- Readable exactly when its deck is. Writes go through the API only.
drop policy if exists "flashcards_read" on public.flashcards;
create policy "flashcards_read"
  on public.flashcards
  for select
  to anon, authenticated
  using (public.deck_is_readable(deck_id));

create table if not exists public.flashcard_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  deck_id uuid not null references public.decks(id) on delete cascade,
  ease numeric(4, 2) not null default 2.50,
  interval_days numeric(7, 2) not null default 0,
  repetitions integer not null default 0,
  lapses integer not null default 0,
  last_rating text check (last_rating in ('again', 'hard', 'good', 'easy')),
  due_at timestamptz,
  last_reviewed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, flashcard_id)
);

create index if not exists flashcard_state_user_due_idx
  on public.flashcard_state (user_id, due_at);

create index if not exists flashcard_state_user_deck_idx
  on public.flashcard_state (user_id, deck_id);

alter table public.flashcard_state enable row level security;

-- A student reads their own review state and nobody else's. Writes go
-- through /api/flashcards/review, which also credits the topic's mastery.
drop policy if exists "flashcard_state_read_own" on public.flashcard_state;
create policy "flashcard_state_read_own"
  on public.flashcard_state
  for select
  to authenticated
  using (user_id = auth.uid());

-- ----------------------------------------------------------- confidence

alter table if exists public.match_answers
  add column if not exists confidence text
    check (confidence in ('sure', 'unsure', 'guess'));

alter table if exists public.topic_review_schedule
  add column if not exists confident_misses integer not null default 0;

comment on column public.topic_review_schedule.confident_misses is
  'Answers the student marked "sure" and got wrong: misconceptions, not slips.';

-- ------------------------------------------------------ learner profile

alter table if exists public.profiles
  add column if not exists education_level text,
  add column if not exists target_exam text,
  add column if not exists exam_date date,
  add column if not exists daily_goal integer,
  add column if not exists onboarded_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_daily_goal_range'
  ) then
    alter table public.profiles
      add constraint profiles_daily_goal_range
      check (daily_goal is null or (daily_goal between 5 and 200));
  end if;
end $$;

-- ------------------------------------------------ mistake explanations

-- The breakdown of one wrong answer, cached by (question, chosen option).
-- Every student who picks the same wrong option on the same question gets
-- the same misconception analysis; writing it again each time cost a model
-- call and several seconds of the student waiting on a wrong answer. Holds
-- no student data: the key is a question id and a hash of an option's text.
create table if not exists public.mistake_explanations (
  question_id uuid not null references public.questions(id) on delete cascade,
  answer_hash text not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  primary key (question_id, answer_hash)
);

-- Service role only: no policies, so the browser can neither read nor write.
alter table public.mistake_explanations enable row level security;


-- ======================================================================
-- WHAT YOU SHOULD SEE AFTERWARDS
-- ======================================================================
--
-- 1. Browser profile updates are limited to two columns. This should list
--    exactly display_name and roasts_enabled:
--
--      select column_name from information_schema.column_privileges
--      where table_schema = 'public' and table_name = 'profiles'
--        and grantee = 'authenticated' and privilege_type = 'UPDATE';
--
-- 2. An anonymous read of decks returns only published ones. In the SQL
--    editor, as the anon role:
--
--      set role anon;
--      select count(*) from public.decks where coalesce(is_public, false) = false;
--      reset role;
--
--    should be 0 (unless a deck has an active challenge link or is a
--    classroom deck, which are shared on purpose).
--
-- 3. The new tables exist:
--
--      select to_regclass('public.flashcards'), to_regclass('public.flashcard_state'),
--             to_regclass('public.mistake_explanations');
