-- An original JEE Main question bank.
--
-- Every item was written for this file. Nothing reproduces, paraphrases or
-- is derived from an NTA paper -- past JEE papers are copyrighted and the
-- copies circulating online are not licensed material. What is taken from
-- the NTA is the published pattern (25 items per subject, 20 multiple choice
-- and 5 numerical, +4/-1) and the NCERT syllabus those items are drawn from.
--
-- Two constraints shaped the content:
--
-- Every answer here is checkable by hand in under a minute. That is
-- deliberate -- an item whose key I cannot verify from first principles is
-- an item I should not be shipping to someone sitting an engineering
-- entrance exam. The numbers are chosen to come out clean for the same
-- reason.
--
-- Distractors are wrong ANSWERS, not wrong topics. Each one is where a
-- specific, common error lands: forgetting to resolve a component, using
-- diameter for radius, dropping a factor of two from an integral. A
-- distractor nobody would pick is a wasted option and turns a four-option
-- item into a two-option one.
--
-- GENERATED by scripts/build-bank-sql.mjs from scripts/banks/jeeMain.ts. Edit the bank and
-- regenerate rather than editing this file: the answer keys below were
-- redistributed and every letter reference in the explanations rewritten to
-- match, and doing that by hand is how a bank ends up with an explanation
-- arguing for a letter that is no longer the key.
--
-- Idempotent through the (exam_id, stimulus + question_text) unique index.

insert into public.diagnostic_questions
  (exam_id, section, domain, skill, difficulty, question_type, stimulus, question_text, answer_choices, correct_answer, explanation, status, source_type, reviewed_at)
select e.id, v.section, v.domain, v.skill, v.difficulty, v.question_type, v.stimulus, v.question_text, v.answer_choices::jsonb, v.correct_answer, v.explanation, 'published', 'human_authored', now()
from public.exam_definitions e
cross join (values

  ('physics', 'Kinematics', 'Projectile motion', 'easy', 'multiple_choice',
   null,
   'A ball is thrown at 20 m/s at 30 degrees above the horizontal. Taking g as 10 m/s squared, what is the maximum height it reaches?',
   '[{"id":"A","text":"5 m"},{"id":"B","text":"10 m"},{"id":"C","text":"20 m"},{"id":"D","text":"2.5 m"}]',
   'A', 'Only the vertical component decides the height. It is 20 sin 30, which is 10 m/s, and the ball rises until that is spent: h equals v squared over 2g, so 100 over 20, which is 5 m. Choosing 20 m is what happens if you use the full 20 m/s instead of resolving it first -- the single most common slip on this item type.'),

  ('physics', 'Laws of motion', 'Motion on an incline', 'easy', 'multiple_choice',
   null,
   'A block slides down a frictionless incline of 30 degrees. Taking g as 10 m/s squared, what is its acceleration along the incline?',
   '[{"id":"A","text":"10 m/s squared"},{"id":"B","text":"5 m/s squared"},{"id":"C","text":"8.7 m/s squared"},{"id":"D","text":"Zero"}]',
   'B', 'The component of gravity along the surface is g sin theta, so 10 times 0.5, which is 5 m/s squared. The 8.7 option is g cos 30 -- the component pressing into the surface, which the normal force cancels and which never drives the slide.'),

  ('physics', 'Work, energy and power', 'Work-energy theorem', 'easy', 'multiple_choice',
   null,
   'A constant force of 8 N acts through 4 m on a 4 kg block initially at rest on a frictionless surface. What is its final speed?',
   '[{"id":"A","text":"2 m/s"},{"id":"B","text":"8 m/s"},{"id":"C","text":"4 m/s"},{"id":"D","text":"16 m/s"}]',
   'C', 'Work done is 8 times 4, which is 32 J, and with no friction all of it becomes kinetic energy. Setting half m v squared equal to 32 with m of 4 gives v squared of 16, so v is 4 m/s. This is faster than finding the acceleration first, and the work-energy theorem is usually the shortcut whenever a question gives force and distance rather than force and time.'),

  ('physics', 'Rotational motion', 'Rolling without slipping', 'hard', 'multiple_choice',
   null,
   'A solid sphere rolls without slipping. What fraction of its total kinetic energy is rotational?',
   '[{"id":"A","text":"1/2"},{"id":"B","text":"5/7"},{"id":"C","text":"2/5"},{"id":"D","text":"2/7"}]',
   'D', 'For a solid sphere the moment of inertia is two fifths m r squared, and rolling without slipping means omega equals v over r. Rotational energy is then one fifth m v squared and translational is one half m v squared, giving seven tenths m v squared in total. The rotational share is one fifth divided by seven tenths, which is two sevenths. Choosing 2/5 is quoting the moment of inertia coefficient rather than computing the ratio.'),

  ('physics', 'Oscillations', 'Simple harmonic motion', 'medium', 'multiple_choice',
   null,
   'A mass on a spring has period T. If the mass is made four times larger and the spring is unchanged, the new period is:',
   '[{"id":"A","text":"2T"},{"id":"B","text":"4T"},{"id":"C","text":"T/2"},{"id":"D","text":"T"}]',
   'A', 'The period is two pi times the square root of m over k, so it depends on the square root of the mass. Four times the mass multiplies the period by the square root of four, which is two. Answering 4T treats the relationship as linear, which is the error this item is built to catch.'),

  ('physics', 'Thermodynamics', 'First law', 'medium', 'multiple_choice',
   null,
   'An ideal gas expands isothermally and reversibly. Which statement is correct?',
   '[{"id":"A","text":"The heat absorbed equals the change in internal energy"},{"id":"B","text":"The heat absorbed equals the work done by the gas"},{"id":"C","text":"No heat is exchanged with the surroundings"},{"id":"D","text":"The work done by the gas is zero"}]',
   'B', 'Internal energy of an ideal gas depends only on temperature, so an isothermal change means the internal energy change is zero. The first law then reduces to heat in equals work out. The option about no heat exchange describes an adiabatic process, which is a different constraint entirely.'),

  ('physics', 'Electrostatics', 'Coulomb''s law', 'easy', 'multiple_choice',
   null,
   'Two point charges attract each other with force F. If the separation between them is doubled and the charges are unchanged, the new force is:',
   '[{"id":"A","text":"2F"},{"id":"B","text":"F/2"},{"id":"C","text":"F/4"},{"id":"D","text":"4F"}]',
   'C', 'Coulomb''s law is an inverse square law, so doubling the separation divides the force by four. Answering F/2 treats it as inverse linear, which is the trap; the same reasoning applies to gravitation, which is why this relationship is worth being automatic about.'),

  ('physics', 'Current electricity', 'Resistors in parallel', 'easy', 'multiple_choice',
   null,
   'A 6 ohm resistor and a 3 ohm resistor are connected in parallel. What is the equivalent resistance?',
   '[{"id":"A","text":"18 ohm"},{"id":"B","text":"9 ohm"},{"id":"C","text":"4.5 ohm"},{"id":"D","text":"2 ohm"}]',
   'D', 'For two resistors in parallel the equivalent is the product over the sum: 18 over 9, which is 2 ohm. A useful check is that a parallel combination is always smaller than the smallest resistor present, so 4.5 and 9 can be rejected on sight without any arithmetic.'),

  ('physics', 'Ray optics', 'Thin lens imaging', 'medium', 'multiple_choice',
   null,
   'An object is placed at a distance of twice the focal length from a converging lens. The image formed is:',
   '[{"id":"A","text":"real, inverted and the same size as the object"},{"id":"B","text":"virtual, upright and magnified"},{"id":"C","text":"real, inverted and magnified"},{"id":"D","text":"virtual, inverted and diminished"}]',
   'A', 'Putting u at 2f into the lens equation gives v at 2f on the far side, so the magnification is exactly one. This is the crossover case: closer than 2f the image is magnified, further away it is diminished. Note also that a real image from a single converging lens is always inverted, which makes the virtual-and-inverted option impossible on its own terms.'),

  ('physics', 'Modern physics', 'Photoelectric effect', 'medium', 'multiple_choice',
   null,
   'In a photoelectric experiment, increasing the intensity of the incident light while keeping its frequency fixed will:',
   '[{"id":"A","text":"increase the maximum kinetic energy of the photoelectrons"},{"id":"B","text":"increase the number of photoelectrons but not their maximum kinetic energy"},{"id":"C","text":"increase both the number and the maximum kinetic energy"},{"id":"D","text":"have no effect on the emitted photoelectrons"}]',
   'B', 'Intensity is the number of photons per second, so it sets how many electrons are ejected. The energy each electron carries away comes from a single photon and depends on frequency alone, through h nu minus the work function. This split is the whole reason the photoelectric effect could not be explained by a wave picture, in which brighter light should have meant faster electrons.'),

  ('physics', 'Kinetic theory', 'Molecular speeds', 'hard', 'multiple_choice',
   null,
   'The root mean square speed of oxygen molecules at temperature T is v. At the same temperature, the rms speed of hydrogen molecules, which have one sixteenth the molar mass, is:',
   '[{"id":"A","text":"v/4"},{"id":"B","text":"16v"},{"id":"C","text":"4v"},{"id":"D","text":"v"}]',
   'C', 'The rms speed goes as the square root of T over M. At the same temperature only the mass matters, and one sixteenth the mass means four times the speed. Answering 16v forgets the square root; this is also why light gases escape a planet''s atmosphere preferentially.'),

  ('physics', 'Electromagnetic induction', 'Lenz''s law', 'medium', 'multiple_choice',
   null,
   'A bar magnet is pushed north-pole-first towards a closed conducting loop. The induced current in the loop, viewed from the magnet''s side, flows so as to:',
   '[{"id":"A","text":"be zero, because the loop has no source of emf"},{"id":"B","text":"assist the approach, presenting a south pole towards the magnet"},{"id":"C","text":"flow only after the magnet stops moving"},{"id":"D","text":"oppose the approach, presenting a north pole towards the magnet"}]',
   'D', 'Lenz''s law says the induced effect opposes the change producing it, so the loop presents a like pole and repels the incoming magnet. The alternative would have the loop pull the magnet in, accelerating it, producing more current, and creating energy from nothing. The loop''s emf is the changing flux itself, which is why the last option is wrong.'),

  ('chemistry', 'Some basic concepts', 'Mole concept', 'easy', 'multiple_choice',
   null,
   'How many moles of carbon dioxide are present in 88 g of the gas? (Molar mass 44 g/mol)',
   '[{"id":"A","text":"2 mol"},{"id":"B","text":"1 mol"},{"id":"C","text":"4 mol"},{"id":"D","text":"0.5 mol"}]',
   'A', 'Moles are mass divided by molar mass: 88 over 44, which is 2. Answering 0.5 inverts the division, which is worth guarding against by sanity check -- a sample heavier than one molar mass must contain more than one mole.'),

  ('chemistry', 'Periodic properties', 'Ionisation enthalpy', 'medium', 'multiple_choice',
   null,
   'Which correctly describes the trend in first ionisation enthalpy on moving left to right across a period?',
   '[{"id":"A","text":"It generally decreases, because atomic radius decreases"},{"id":"B","text":"It generally increases, because nuclear charge rises while shielding stays nearly constant"},{"id":"C","text":"It stays constant, because the number of shells does not change"},{"id":"D","text":"It generally decreases, because electrons are added to the same shell"}]',
   'B', 'Across a period the added electrons enter the same shell, so they shield each other poorly while the nuclear charge keeps climbing. The outer electrons are held more tightly and are harder to remove. Note that a smaller radius makes removal harder, not easier, which is why the second option has the right fact attached to the wrong conclusion.'),

  ('chemistry', 'Chemical bonding', 'VSEPR and hybridisation', 'medium', 'multiple_choice',
   null,
   'Ammonia has a bond angle of about 107 degrees rather than the 109.5 degrees of a regular tetrahedron. The best explanation is that:',
   '[{"id":"A","text":"the N-H bonds are shorter than a tetrahedral geometry requires"},{"id":"B","text":"nitrogen is sp2 hybridised rather than sp3"},{"id":"C","text":"the lone pair repels the bonding pairs more strongly than they repel each other"},{"id":"D","text":"hydrogen atoms repel one another more strongly than the lone pair does"}]',
   'C', 'Nitrogen is sp3 hybridised with four electron domains, but one is a lone pair. A lone pair is held closer to the nucleus and spreads out more, so it squeezes the three bonding pairs together and the angle closes slightly below the ideal. The same reasoning predicts the further reduction to about 104.5 degrees in water, which has two lone pairs.'),

  ('chemistry', 'Chemical kinetics', 'First-order reactions', 'medium', 'multiple_choice',
   null,
   'For a first-order reaction, the half-life is:',
   '[{"id":"A","text":"proportional to the square of the initial concentration"},{"id":"B","text":"directly proportional to the initial concentration"},{"id":"C","text":"inversely proportional to the initial concentration"},{"id":"D","text":"independent of the initial concentration"}]',
   'D', 'For first order, the half-life is 0.693 over k, and no concentration term appears. This is why radioactive decay has a fixed half-life regardless of sample size. It is specific to first order: a second-order half-life does depend on the starting concentration, so the property is a useful way to identify the order from data.'),

  ('chemistry', 'Organic chemistry', 'Nucleophilic substitution', 'hard', 'multiple_choice',
   null,
   'Tertiary alkyl halides undergo substitution predominantly by the SN1 mechanism rather than SN2 mainly because:',
   '[{"id":"A","text":"the tertiary carbocation intermediate is stabilised and the crowded carbon blocks backside attack"},{"id":"B","text":"tertiary halides have unusually weak carbon-halogen bonds"},{"id":"C","text":"the nucleophile is more reactive towards tertiary carbon"},{"id":"D","text":"SN2 requires a carbocation, which tertiary halides cannot form"}]',
   'A', 'Two effects push the same way. Electronically, three alkyl groups donate electron density and stabilise the carbocation that SN1 must form. Sterically, those same groups block the backside approach SN2 needs. The last option inverts the mechanisms: it is SN1 that goes through a carbocation, while SN2 is a single concerted step with no intermediate at all.'),

  ('chemistry', 'Organic chemistry', 'Structural isomerism', 'easy', 'multiple_choice',
   null,
   'How many structural isomers does butane, C4H10, have?',
   '[{"id":"A","text":"3"},{"id":"B","text":"2"},{"id":"C","text":"4"},{"id":"D","text":"1"}]',
   'B', 'There are two: the straight chain n-butane, and the branched isobutane, which is 2-methylpropane. Drawing what looks like a third by bending the chain on paper is the usual error -- a bent chain is the same molecule viewed differently, since a structural isomer requires a genuinely different connectivity.'),

  ('chemistry', 'Thermodynamics', 'Gibbs free energy', 'medium', 'multiple_choice',
   null,
   'A reaction is endothermic and results in an increase in entropy. It will be spontaneous:',
   '[{"id":"A","text":"at all temperatures"},{"id":"B","text":"at low temperatures only"},{"id":"C","text":"at high temperatures only"},{"id":"D","text":"at no temperature"}]',
   'C', 'Spontaneity requires a negative change in Gibbs energy, which is delta H minus T delta S. Here delta H is positive, which works against it, but delta S is also positive, so the minus T delta S term becomes more negative as temperature rises. Above a threshold temperature the entropy term wins. This is precisely why ice melts spontaneously above zero degrees and not below it.'),

  ('chemistry', 'Coordination compounds', 'Oxidation state', 'easy', 'multiple_choice',
   null,
   'What is the oxidation state of cobalt in the complex ion hexaamminecobalt(III), written as Co(NH3)6 with an overall charge of 3+?',
   '[{"id":"A","text":"0"},{"id":"B","text":"+2"},{"id":"C","text":"+6"},{"id":"D","text":"+3"}]',
   'D', 'Ammonia is a neutral ligand, contributing nothing to the charge, so the metal must carry the entire 3+ by itself. Answering +6 comes from counting the six ligands rather than their charge; the count of ligands is the coordination number, which is a separate property from oxidation state.'),

  ('chemistry', 'Equilibrium', 'Le Chatelier''s principle', 'medium', 'multiple_choice',
   null,
   'For the equilibrium N2(g) + 3H2(g) in balance with 2NH3(g), which change shifts the position of equilibrium towards ammonia?',
   '[{"id":"A","text":"Increasing the total pressure"},{"id":"B","text":"Decreasing the total pressure"},{"id":"C","text":"Adding a catalyst"},{"id":"D","text":"Increasing the volume of the vessel"}]',
   'A', 'There are four moles of gas on the left and two on the right, so raising the pressure favours the side that occupies less volume. A catalyst is worth singling out: it speeds both directions equally and changes how fast equilibrium arrives, never where it sits. Increasing the volume is the same as lowering the pressure, so it shifts the other way.'),

  ('chemistry', 'Solutions', 'Colligative properties', 'hard', 'multiple_choice',
   null,
   'Equimolar aqueous solutions of glucose and sodium chloride are compared. The depression in freezing point of the sodium chloride solution is approximately:',
   '[{"id":"A","text":"the same as that of the glucose solution"},{"id":"B","text":"twice that of the glucose solution"},{"id":"C","text":"half that of the glucose solution"},{"id":"D","text":"unrelated, because the two solutes differ chemically"}]',
   'B', 'Colligative properties count dissolved particles rather than caring what they are. Glucose dissolves as single molecules, while sodium chloride dissociates into two ions, so an equimolar solution contains roughly twice as many particles and depresses the freezing point about twice as much. This particle count is the van''t Hoff factor, and it is the whole reason salt is spread on icy roads rather than sugar.'),

  ('chemistry', 'Electrochemistry', 'Electrode potential', 'medium', 'multiple_choice',
   null,
   'In a galvanic cell operating spontaneously, the electrode at which oxidation occurs is:',
   '[{"id":"A","text":"the anode, which is the positive terminal"},{"id":"B","text":"the cathode, which is the negative terminal"},{"id":"C","text":"the anode, which is the negative terminal"},{"id":"D","text":"the cathode, which is the positive terminal"}]',
   'C', 'Oxidation always happens at the anode, in every cell, by definition. What flips between galvanic and electrolytic cells is the sign: in a galvanic cell the anode releases electrons into the external circuit and is therefore negative, while in electrolysis the anode is driven positive by the supply. Tying the sign to the process rather than memorising it is what stops this being confusing.'),

  ('chemistry', 'Organic chemistry', 'Aromaticity', 'hard', 'multiple_choice',
   null,
   'According to Huckel''s rule, a planar cyclic conjugated species is aromatic when its delocalised system contains:',
   '[{"id":"A","text":"any even number of pi electrons"},{"id":"B","text":"4n pi electrons, where n is a positive integer"},{"id":"C","text":"exactly six pi electrons in all cases"},{"id":"D","text":"4n + 2 pi electrons, where n is zero or a positive integer"}]',
   'D', 'The count is 4n + 2, giving the aromatic series 2, 6, 10 and so on. Benzene is the familiar case at six, but the cyclopropenyl cation is aromatic with two, which is why the exactly-six option is too narrow. A 4n count such as cyclobutadiene''s four is antiaromatic and markedly unstable, so the even-number option is wrong in a way that matters.'),

  ('mathematics', 'Quadratic equations', 'Sum and product of roots', 'easy', 'multiple_choice',
   null,
   'If the roots of x squared minus 5x + 6 equal zero are alpha and beta, what is the value of alpha squared plus beta squared?',
   '[{"id":"A","text":"13"},{"id":"B","text":"25"},{"id":"C","text":"12"},{"id":"D","text":"1"}]',
   'A', 'The sum of the roots is 5 and the product is 6. Using the identity that alpha squared plus beta squared equals the sum squared minus twice the product gives 25 minus 12, which is 13. Answering 25 stops at the sum squared and forgets to subtract; the identity is worth knowing because it avoids solving for the roots at all.'),

  ('mathematics', 'Sequences and series', 'Arithmetic progression', 'easy', 'multiple_choice',
   null,
   'What is the sum of the first 20 terms of the arithmetic progression 3, 7, 11, 15, ...?',
   '[{"id":"A","text":"800"},{"id":"B","text":"820"},{"id":"C","text":"410"},{"id":"D","text":"1640"}]',
   'B', 'The first term is 3 and the common difference is 4. The sum of n terms is n over 2 times twice the first term plus n minus one times d, giving 10 times 6 plus 76, which is 10 times 82, so 820. Answering 410 is the result of dropping the factor from n over 2.'),

  ('mathematics', 'Calculus', 'Differentiation', 'medium', 'multiple_choice',
   null,
   'What is the derivative of x squared times sin x with respect to x?',
   '[{"id":"A","text":"x squared cos x"},{"id":"B","text":"2x cos x"},{"id":"C","text":"2x sin x + x squared cos x"},{"id":"D","text":"2x sin x - x squared cos x"}]',
   'C', 'This is a product, so the product rule applies: the derivative of the first times the second, plus the first times the derivative of the second. That gives 2x sin x plus x squared cos x. The two shorter options each differentiate one factor and forget the other, which is the error the product rule exists to prevent.'),

  ('mathematics', 'Calculus', 'Definite integration', 'medium', 'multiple_choice',
   null,
   'What is the value of the definite integral of sin x from 0 to pi?',
   '[{"id":"A","text":"pi"},{"id":"B","text":"0"},{"id":"C","text":"1"},{"id":"D","text":"2"}]',
   'D', 'The antiderivative of sin x is minus cos x. Evaluating from 0 to pi gives minus cos pi minus minus cos 0, which is 1 plus 1, so 2. Answering 0 is what you get by integrating over a full period from 0 to 2 pi, where the positive and negative halves cancel -- over 0 to pi the curve is entirely above the axis, so the area cannot be zero.'),

  ('mathematics', 'Probability', 'Conditional probability', 'hard', 'multiple_choice',
   null,
   'Two fair dice are rolled. Given that the sum is 8, what is the probability that at least one die shows a 5?',
   '[{"id":"A","text":"2/5"},{"id":"B","text":"1/5"},{"id":"C","text":"1/3"},{"id":"D","text":"2/9"}]',
   'A', 'The outcomes summing to 8 are (2,6), (3,5), (4,4), (5,3) and (6,2), so five equally likely cases. Two of them contain a 5, giving two fifths. The common mistake is to use the unconditional probability of rolling a 5; being told the sum restricts the sample space to those five outcomes, and every conditional probability question turns on rebuilding that space correctly.'),

  ('mathematics', 'Complex numbers', 'Modulus and powers', 'medium', 'multiple_choice',
   null,
   'What is the value of i raised to the power 2026?',
   '[{"id":"A","text":"1"},{"id":"B","text":"-1"},{"id":"C","text":"i"},{"id":"D","text":"-i"}]',
   'B', 'Powers of i repeat with period four, so only the remainder on division by four matters. 2026 leaves a remainder of 2, and i squared is minus 1. Reducing the exponent modulo four turns any power of i into one of four cases and makes this instant.'),

  ('mathematics', 'Matrices and determinants', 'Determinant properties', 'medium', 'multiple_choice',
   null,
   'If A is a 3 by 3 matrix with determinant 4, what is the determinant of 2A?',
   '[{"id":"A","text":"4"},{"id":"B","text":"8"},{"id":"C","text":"32"},{"id":"D","text":"64"}]',
   'C', 'Scaling a matrix multiplies every one of its n rows by the scalar, so the determinant is multiplied by the scalar to the power n. Here that is 2 cubed times 4, which is 32. Answering 8 applies the factor only once, which is the standard trap on this identity.'),

  ('mathematics', 'Coordinate geometry', 'Straight lines', 'easy', 'multiple_choice',
   null,
   'What is the slope of a line perpendicular to the line 2x + 3y = 6?',
   '[{"id":"A","text":"2/3"},{"id":"B","text":"-2/3"},{"id":"C","text":"-3/2"},{"id":"D","text":"3/2"}]',
   'D', 'Rearranging gives y equals minus two thirds x plus 2, so the slope is minus two thirds. Perpendicular slopes multiply to minus one, so the answer is the negative reciprocal, three halves. Answering minus two thirds gives the slope of the original line rather than the perpendicular one.'),

  ('mathematics', 'Calculus', 'Limits', 'medium', 'multiple_choice',
   null,
   'What is the limit of sin(3x) divided by x as x approaches zero?',
   '[{"id":"A","text":"3"},{"id":"B","text":"1"},{"id":"C","text":"0"},{"id":"D","text":"1/3"}]',
   'A', 'The standard limit is that sin u over u tends to 1. Writing sin 3x over x as 3 times sin 3x over 3x makes the inner quotient tend to 1, leaving 3. Answering 1 applies the standard limit without accounting for the coefficient inside the sine.'),

  ('mathematics', 'Binomial theorem', 'General term', 'hard', 'multiple_choice',
   null,
   'What is the coefficient of x cubed in the expansion of (1 + x) to the power 6?',
   '[{"id":"A","text":"15"},{"id":"B","text":"20"},{"id":"C","text":"6"},{"id":"D","text":"120"}]',
   'B', 'The coefficient is 6 choose 3, which is 6 factorial over 3 factorial times 3 factorial, so 720 over 36, giving 20. Answering 120 computes a permutation instead of a combination; order does not matter when selecting which factors contribute an x, so the division by 3 factorial is required.'),

  ('mathematics', 'Vectors', 'Scalar product', 'medium', 'multiple_choice',
   null,
   'For non-zero vectors a and b, the scalar product a dot b equals zero implies that:',
   '[{"id":"A","text":"at least one of a and b is the zero vector"},{"id":"B","text":"a and b are parallel"},{"id":"C","text":"a and b are perpendicular"},{"id":"D","text":"a and b are equal in magnitude"}]',
   'C', 'The scalar product is the product of the magnitudes times cos theta. With both vectors non-zero, the product vanishes only when cos theta is zero, which means an angle of 90 degrees. Parallel vectors are the opposite case, where cos theta is one and the scalar product is at its maximum.'),

  ('mathematics', 'Trigonometry', 'Identities', 'easy', 'multiple_choice',
   null,
   'What is the exact value of sin 75 degrees?',
   '[{"id":"A","text":"1/2"},{"id":"B","text":"(square root of 6 minus square root of 2) divided by 4"},{"id":"C","text":"(square root of 3 plus 1) divided by 2"},{"id":"D","text":"(square root of 6 plus square root of 2) divided by 4"}]',
   'D', 'Write 75 as 45 plus 30 and expand: sin 45 cos 30 plus cos 45 sin 30. That gives root 6 over 4 plus root 2 over 4, so root 6 plus root 2 all over 4. The option with a minus sign is sin 15 degrees, which comes from the same expansion with 45 minus 30 -- a quick sanity check is that sin 75 must be close to 1, and this value is about 0.966.')

) as v(section, domain, skill, difficulty, question_type, stimulus, question_text, answer_choices, correct_answer, explanation)
where e.slug = 'jee-main'
on conflict do nothing;

-- Switched on only now, with a bank behind it.
update public.exam_definitions
set status = 'available'
where slug = 'jee-main';
