-- An original NEET UG question bank.
--
-- Every item was written for this file. Nothing reproduces, paraphrases or is
-- derived from an NTA paper. What is taken from the NTA is the published 2026
-- pattern -- 180 compulsory questions, Physics 45, Chemistry 45, Biology 90,
-- at +4 and -1 -- and the NCERT syllabus the paper is drawn from.
--
-- Biology carries half the paper and is weighted accordingly here. That is
-- not padding: Biology is 360 of the 720 marks, and a NEET bank that treats
-- it as one subject among three trains the wrong allocation of attention.
--
-- Explanations name the answer by its CONTENT rather than by its letter
-- ("the option giving two ions"), because the keys are redistributed at build
-- time. An explanation that says "option B" is one rebalance away from
-- arguing for a letter that is no longer the key.
--
-- GENERATED by scripts/build-bank-sql.mjs from scripts/banks/neetUg.ts. Edit the bank and
-- regenerate rather than editing this file: the answer keys below were
-- redistributed and every letter reference in the explanations rewritten to
-- match, and doing that by hand is how a bank ends up with an explanation
-- arguing for a letter that is no longer the key.
--
-- Idempotent through the (exam_id, stimulus + question_text) unique index.

insert into public.diagnostic_questions
  (exam_id, section, domain, skill, difficulty, question_type, stimulus, question_text, answer_choices, correct_answer, explanation, status, source_type, reviewed_at)
select e.id, v.section, v.domain, v.skill, v.difficulty, v.question_type, v.stimulus, v.question_text, v.answer_choices::jsonb, v.correct_answer, v.explanation, 'published', 'human_authored', now()
from public.exam_definitions e
cross join (values

  ('physics', 'Laws of motion', 'Friction', 'easy', 'multiple_choice',
   null,
   'A block of mass 2 kg rests on a horizontal surface with coefficient of static friction 0.4. Taking g as 10 m/s squared, what is the maximum friction force before it begins to slide?',
   '[{"id":"A","text":"8 N"},{"id":"B","text":"20 N"},{"id":"C","text":"0.8 N"},{"id":"D","text":"5 N"}]',
   'A', 'Limiting friction is the coefficient times the normal force. The normal force here is the weight, 2 times 10, which is 20 N, so the maximum friction is 0.4 times 20, giving 8 N. Answering 20 N quotes the normal force itself and forgets to apply the coefficient.'),

  ('physics', 'Work, energy and power', 'Conservation of energy', 'medium', 'multiple_choice',
   null,
   'A body is dropped from rest at a height of 20 m. Ignoring air resistance and taking g as 10 m/s squared, what is its speed just before it hits the ground?',
   '[{"id":"A","text":"10 m/s"},{"id":"B","text":"20 m/s"},{"id":"C","text":"40 m/s"},{"id":"D","text":"200 m/s"}]',
   'B', 'All the potential energy becomes kinetic, so mgh equals half m v squared and the mass cancels. That leaves v squared equal to 2gh, which is 2 times 10 times 20, or 400, so the speed is 20 m/s. The mass cancelling is the point worth carrying away: a heavy and a light body arrive together in the absence of air resistance.'),

  ('physics', 'Current electricity', 'Ohm''s law and power', 'medium', 'multiple_choice',
   null,
   'A 60 W bulb is designed for 120 V. What is its resistance when operating normally?',
   '[{"id":"A","text":"120 ohm"},{"id":"B","text":"2 ohm"},{"id":"C","text":"240 ohm"},{"id":"D","text":"7200 ohm"}]',
   'C', 'Power equals V squared over R, so R is V squared over P: 14400 divided by 60, which is 240 ohm. Answering 2 ohm comes from dividing voltage by power, which is not a form of Ohm''s law and does not have units of resistance -- a dimension check catches it immediately.'),

  ('physics', 'Optics', 'Refraction', 'medium', 'multiple_choice',
   null,
   'Light passes from air into glass. Which quantity remains unchanged?',
   '[{"id":"A","text":"Direction of travel"},{"id":"B","text":"Speed"},{"id":"C","text":"Wavelength"},{"id":"D","text":"Frequency"}]',
   'D', 'Frequency is set by the source and cannot change at a boundary; if it did, wave crests would have to pile up or vanish at the interface. Speed falls in the denser medium, and since speed equals frequency times wavelength, the wavelength falls with it. The direction changes too, unless the light arrives along the normal.'),

  ('physics', 'Modern physics', 'Nuclear binding energy', 'hard', 'multiple_choice',
   null,
   'Energy is released in both nuclear fission of heavy nuclei and fusion of light nuclei because in each case the products have:',
   '[{"id":"A","text":"a higher binding energy per nucleon than the reactants"},{"id":"B","text":"a lower binding energy per nucleon than the reactants"},{"id":"C","text":"more nucleons in total than the reactants"},{"id":"D","text":"a greater total mass than the reactants"}]',
   'A', 'Binding energy per nucleon peaks near iron. Moving towards that peak from either direction -- splitting something heavier or combining something lighter -- gives products that are more tightly bound, and the difference is released. The mass option is the wrong way round: the products are lighter, and that lost mass is the energy, by E equals m c squared.'),

  ('physics', 'Thermodynamics', 'Heat transfer', 'easy', 'multiple_choice',
   null,
   'How much heat is required to raise the temperature of 200 g of water by 10 degrees Celsius? (Specific heat capacity of water is 4.2 J per g per degree)',
   '[{"id":"A","text":"840 J"},{"id":"B","text":"8400 J"},{"id":"C","text":"84000 J"},{"id":"D","text":"420 J"}]',
   'B', 'Heat equals mass times specific heat times temperature change: 200 times 4.2 times 10, which is 8400 J. Water''s unusually high specific heat is why it is used as a coolant and why coastal climates are milder than inland ones.'),

  ('physics', 'Kinematics', 'Graphs of motion', 'medium', 'multiple_choice',
   null,
   'For an object accelerating uniformly from rest, the graph of displacement against time is:',
   '[{"id":"A","text":"a horizontal line"},{"id":"B","text":"a straight line through the origin"},{"id":"C","text":"a parabola"},{"id":"D","text":"a hyperbola"}]',
   'C', 'With constant acceleration from rest, displacement is half a t squared, so it grows as the square of time and traces a parabola. A straight line would mean constant velocity, which is the case of zero acceleration -- that describes the velocity-time graph here, not the displacement one.'),

  ('physics', 'Gravitation', 'Orbital motion', 'hard', 'multiple_choice',
   null,
   'A satellite is moved into an orbit of four times its original radius around the Earth. Its orbital speed becomes:',
   '[{"id":"A","text":"unchanged"},{"id":"B","text":"twice the original"},{"id":"C","text":"one quarter of the original"},{"id":"D","text":"half the original"}]',
   'D', 'Orbital speed is the square root of GM over r, so it varies inversely with the square root of the radius, and four times the radius halves the speed. Higher orbits are slower, which is why a geostationary satellite takes a full day to circle while the space station takes about ninety minutes.'),

  ('physics', 'Magnetism', 'Force on a moving charge', 'medium', 'multiple_choice',
   null,
   'A charged particle travels parallel to a uniform magnetic field. The magnetic force acting on it is:',
   '[{"id":"A","text":"zero"},{"id":"B","text":"maximum"},{"id":"C","text":"directed along the field"},{"id":"D","text":"directed opposite to its motion"}]',
   'A', 'The magnetic force is qvB sin theta, and the angle between velocity and field is zero here, so the force vanishes. It is greatest when the particle moves perpendicular to the field. The force is also always perpendicular to the velocity, which is why a magnetic field can bend a path but never change a particle''s speed or do work on it.'),

  ('physics', 'Waves', 'Doppler effect', 'medium', 'multiple_choice',
   null,
   'A stationary observer hears the siren of an approaching ambulance. Compared with the emitted sound, the observer hears:',
   '[{"id":"A","text":"a higher frequency, with the speed of sound increased"},{"id":"B","text":"a higher frequency, with the speed of sound unchanged"},{"id":"C","text":"a lower frequency, with the speed of sound unchanged"},{"id":"D","text":"the same frequency, with only the loudness increased"}]',
   'B', 'Approaching motion compresses successive wavefronts, so they arrive more often and the pitch rises. The speed of sound is fixed by the medium -- air temperature and composition -- and does not depend on how fast the source is moving, which is the part most often got wrong.'),

  ('chemistry', 'Atomic structure', 'Quantum numbers', 'medium', 'multiple_choice',
   null,
   'What is the maximum number of electrons that can occupy a 3d subshell?',
   '[{"id":"A","text":"10"},{"id":"B","text":"6"},{"id":"C","text":"14"},{"id":"D","text":"2"}]',
   'A', 'A d subshell has five orbitals and each holds two electrons with opposed spins, giving ten. The other numbers are the capacities of p at six, f at fourteen and a single orbital at two, so knowing the orbital counts of 1, 3, 5 and 7 for s, p, d and f covers every case.'),

  ('chemistry', 'Chemical bonding', 'Intermolecular forces', 'medium', 'multiple_choice',
   null,
   'Water has a much higher boiling point than hydrogen sulfide, despite sulfur being heavier than oxygen. The main reason is:',
   '[{"id":"A","text":"the greater molar mass of water"},{"id":"B","text":"hydrogen bonding between water molecules"},{"id":"C","text":"the ionic character of the O-H bond"},{"id":"D","text":"stronger dispersion forces in water"}]',
   'B', 'Oxygen is small and strongly electronegative, so water forms hydrogen bonds, which are far stronger than the dipole and dispersion forces holding hydrogen sulfide together. Sulfur is too large and not electronegative enough to do the same. Note that water is the lighter molecule, so mass would predict the opposite of what is observed -- that anomaly is exactly what hydrogen bonding explains.'),

  ('chemistry', 'Redox reactions', 'Oxidation number', 'easy', 'multiple_choice',
   null,
   'What is the oxidation number of manganese in the permanganate ion, MnO4 with a charge of 1 minus?',
   '[{"id":"A","text":"+2"},{"id":"B","text":"+4"},{"id":"C","text":"+7"},{"id":"D","text":"-1"}]',
   'C', 'Each oxygen is taken as minus 2, so four of them contribute minus 8. For the ion to carry an overall charge of minus 1, manganese must be plus 7. This is manganese at its maximum oxidation state, which is why permanganate is such a strong oxidising agent -- it has nowhere to go but down.'),

  ('chemistry', 'Organic chemistry', 'Functional groups', 'medium', 'multiple_choice',
   null,
   'Which reagent distinguishes an aldehyde from a ketone?',
   '[{"id":"A","text":"Litmus, which the aldehyde turns red"},{"id":"B","text":"Bromine water, which decolourises with the ketone only"},{"id":"C","text":"Sodium hydroxide, which dissolves the aldehyde only"},{"id":"D","text":"Tollens'' reagent, which gives a silver mirror with the aldehyde only"}]',
   'D', 'An aldehyde has a hydrogen on its carbonyl carbon and is readily oxidised to a carboxylic acid, reducing silver ions to metallic silver and depositing the mirror. A ketone has two alkyl groups there instead and resists oxidation. Bromine water tests for unsaturation and litmus for acidity, neither of which separates these two.'),

  ('chemistry', 'States of matter', 'Gas laws', 'medium', 'multiple_choice',
   null,
   'A fixed mass of ideal gas at constant pressure is heated from 300 K to 600 K. Its volume:',
   '[{"id":"A","text":"doubles"},{"id":"B","text":"halves"},{"id":"C","text":"stays the same"},{"id":"D","text":"quadruples"}]',
   'A', 'At constant pressure, volume is proportional to absolute temperature, and 600 K is twice 300 K, so the volume doubles. The step that matters is using kelvin: doubling 27 degrees Celsius to 54 would not double the volume, because the proportionality only holds from absolute zero.'),

  ('chemistry', 'Biomolecules', 'Proteins', 'medium', 'multiple_choice',
   null,
   'The secondary structure of a protein, such as an alpha helix, is stabilised primarily by:',
   '[{"id":"A","text":"peptide bonds between adjacent amino acids"},{"id":"B","text":"hydrogen bonds between backbone amide and carbonyl groups"},{"id":"C","text":"disulfide bridges between cysteine side chains"},{"id":"D","text":"ionic bonds between charged side chains"}]',
   'B', 'Secondary structure is a pattern in the backbone, held by hydrogen bonds between the N-H of one residue and the C=O of another further along. Peptide bonds define the primary sequence rather than folding it, while disulfide bridges and ionic interactions between side chains belong to tertiary structure.'),

  ('chemistry', 'Ionic equilibrium', 'pH calculation', 'easy', 'multiple_choice',
   null,
   'What is the pH of a 0.001 M solution of hydrochloric acid at 25 degrees Celsius?',
   '[{"id":"A","text":"1"},{"id":"B","text":"11"},{"id":"C","text":"3"},{"id":"D","text":"0.001"}]',
   'C', 'Hydrochloric acid is strong and dissociates completely, so the hydrogen ion concentration is 10 to the minus 3 and the pH is 3. Answering 11 computes the pOH instead; the two must sum to 14, and an acid has to land below 7, which catches the error immediately.'),

  ('chemistry', 'Organic chemistry', 'Optical isomerism', 'hard', 'multiple_choice',
   null,
   'What is required for a carbon atom to be a stereocentre giving rise to optical isomerism?',
   '[{"id":"A","text":"Attachment to an aromatic ring"},{"id":"B","text":"A double bond to an adjacent carbon"},{"id":"C","text":"At least one hydrogen atom attached to it"},{"id":"D","text":"Four different groups attached to it"}]',
   'D', 'A carbon bonded to four different groups has a mirror image that cannot be superimposed on it, giving a pair of enantiomers. If any two of the groups are identical the molecule has an internal mirror plane and is achiral. A double bond produces cis-trans isomerism, which is geometric rather than optical.'),

  ('chemistry', 'Periodic properties', 'Atomic radius', 'medium', 'multiple_choice',
   null,
   'Which of these atoms has the largest atomic radius?',
   '[{"id":"A","text":"Potassium"},{"id":"B","text":"Sodium"},{"id":"C","text":"Lithium"},{"id":"D","text":"Hydrogen"}]',
   'A', 'All four sit in group 1, and atomic radius increases down a group as further electron shells are added. Potassium is the lowest of these and therefore the largest. Across a period the trend runs the other way, because electrons enter the same shell while the nuclear charge keeps rising.'),

  ('chemistry', 'Surface chemistry', 'Catalysis', 'medium', 'multiple_choice',
   null,
   'A catalyst increases the rate of a reaction by:',
   '[{"id":"A","text":"increasing the average kinetic energy of the reactant molecules"},{"id":"B","text":"providing an alternative pathway of lower activation energy"},{"id":"C","text":"shifting the equilibrium position towards the products"},{"id":"D","text":"raising the temperature of the reaction mixture"}]',
   'B', 'A catalyst opens a different route over a lower barrier, so a larger fraction of collisions carries enough energy to react. It does not heat the mixture or alter the energy distribution of the molecules, and it accelerates the forward and reverse reactions equally -- which is precisely why it cannot move the equilibrium position.'),

  ('biology', 'Cell structure and function', 'Organelles', 'easy', 'multiple_choice',
   null,
   'Which organelle is the site of aerobic respiration in eukaryotic cells?',
   '[{"id":"A","text":"Mitochondrion"},{"id":"B","text":"Ribosome"},{"id":"C","text":"Golgi apparatus"},{"id":"D","text":"Lysosome"}]',
   'A', 'The mitochondrion carries out the Krebs cycle and oxidative phosphorylation, producing most of the cell''s ATP. Ribosomes build proteins, the Golgi modifies and dispatches them, and lysosomes digest material -- none of which is respiration.'),

  ('biology', 'Genetics', 'Monohybrid cross', 'medium', 'multiple_choice',
   null,
   'Two heterozygous tall pea plants (Tt) are crossed, where tall is dominant to dwarf. What fraction of the offspring is expected to be dwarf?',
   '[{"id":"A","text":"1/2"},{"id":"B","text":"1/4"},{"id":"C","text":"3/4"},{"id":"D","text":"None"}]',
   'B', 'The cross gives TT, Tt, TT and tt in equal proportion. Only tt is dwarf, so one quarter. The three quarters figure is the tall phenotype, which is the answer to a different question -- and the phenotypic ratio of 3 to 1 hides a genotypic ratio of 1 to 2 to 1.'),

  ('biology', 'Human physiology', 'Circulatory system', 'medium', 'multiple_choice',
   null,
   'Which blood vessel carries oxygenated blood from the lungs to the heart?',
   '[{"id":"A","text":"Aorta"},{"id":"B","text":"Pulmonary artery"},{"id":"C","text":"Pulmonary vein"},{"id":"D","text":"Vena cava"}]',
   'C', 'The pulmonary vein is the exception to the usual rule that veins carry deoxygenated blood: it returns freshly oxygenated blood from the lungs to the left atrium. Its partner the pulmonary artery is the matching exception, carrying deoxygenated blood away from the heart. The definitions of artery and vein rest on direction of flow, not on oxygen content.'),

  ('biology', 'Plant physiology', 'Photosynthesis', 'medium', 'multiple_choice',
   null,
   'In the light-dependent reactions of photosynthesis, the oxygen released originates from:',
   '[{"id":"A","text":"ATP"},{"id":"B","text":"carbon dioxide"},{"id":"C","text":"glucose"},{"id":"D","text":"water"}]',
   'D', 'Photolysis splits water to supply electrons to photosystem II, and the oxygen is the leftover. Carbon dioxide is the intuitive guess and is wrong: its carbon and oxygen end up in carbohydrate during the Calvin cycle. Isotope labelling experiments settled this by tracing heavy oxygen supplied in water into the gas released.'),

  ('biology', 'Molecular biology', 'Central dogma', 'medium', 'multiple_choice',
   null,
   'During transcription in eukaryotes, the enzyme responsible for synthesising messenger RNA is:',
   '[{"id":"A","text":"RNA polymerase II"},{"id":"B","text":"DNA polymerase"},{"id":"C","text":"Ligase"},{"id":"D","text":"Helicase alone"}]',
   'A', 'RNA polymerase II reads the template strand and builds the mRNA transcript. DNA polymerase replicates DNA rather than transcribing it, ligase seals breaks in a backbone, and helicase only unwinds the double helix without synthesising anything.'),

  ('biology', 'Ecology', 'Energy flow', 'medium', 'multiple_choice',
   null,
   'Roughly what proportion of energy is transferred from one trophic level to the next in a typical food chain?',
   '[{"id":"A","text":"About 50 percent"},{"id":"B","text":"About 10 percent"},{"id":"C","text":"About 90 percent"},{"id":"D","text":"Nearly all of it"}]',
   'B', 'Most energy at each level is spent on respiration, movement and heat, leaving only around a tenth available to the level above. This is why food chains rarely exceed four or five links and why a given area supports far more plants than predators.'),

  ('biology', 'Human physiology', 'Excretory system', 'hard', 'multiple_choice',
   null,
   'Most reabsorption of glucose from the glomerular filtrate occurs in the:',
   '[{"id":"A","text":"distal convoluted tubule"},{"id":"B","text":"loop of Henle"},{"id":"C","text":"proximal convoluted tubule"},{"id":"D","text":"collecting duct"}]',
   'C', 'The proximal convoluted tubule reclaims essentially all filtered glucose, along with amino acids and most water and ions, using active transport. Its cells carry a dense brush border of microvilli for exactly this. The loop of Henle concentrates the filtrate, while the distal tubule and collecting duct fine-tune water and salt under hormonal control.'),

  ('biology', 'Cell division', 'Meiosis', 'hard', 'multiple_choice',
   null,
   'Crossing over during meiosis occurs in which stage, and between which structures?',
   '[{"id":"A","text":"Anaphase I, as homologues separate"},{"id":"B","text":"Prophase II, between sister chromatids of the same chromosome"},{"id":"C","text":"Metaphase I, between all four chromatids simultaneously"},{"id":"D","text":"Prophase I, between non-sister chromatids of homologous chromosomes"}]',
   'D', 'Homologues pair during prophase I and exchange segments at chiasmata, and the exchange is between non-sister chromatids -- one from each homologue. Sister chromatids are identical copies, so exchanging material between them would produce no new combinations, which is why the prophase II option describes something with no genetic consequence.'),

  ('biology', 'Evolution', 'Natural selection', 'medium', 'multiple_choice',
   null,
   'A population of bacteria survives a course of antibiotics. The best explanation is that:',
   '[{"id":"A","text":"resistant variants were already present and were the ones that reproduced"},{"id":"B","text":"the bacteria developed resistance in response to the antibiotic"},{"id":"C","text":"the antibiotic caused mutations that produced resistance"},{"id":"D","text":"individual bacteria adapted during their own lifetimes"}]',
   'A', 'Selection acts on variation that already exists: mutation is undirected, and the antibiotic removes the susceptible rather than instructing the survivors. The other options all describe an organism acquiring a trait because it needs it, which is the Lamarckian picture, and it is the single most common misconception about how resistance arises.'),

  ('biology', 'Human physiology', 'Respiratory transport', 'medium', 'multiple_choice',
   null,
   'Most carbon dioxide is carried in the blood as:',
   '[{"id":"A","text":"carbaminohaemoglobin bound within red cells"},{"id":"B","text":"bicarbonate ions in the plasma"},{"id":"C","text":"carbon dioxide gas dissolved in the plasma"},{"id":"D","text":"carbon monoxide complexes"}]',
   'B', 'About seventy percent travels as bicarbonate, formed when carbonic anhydrase inside red cells converts carbon dioxide and water into carbonic acid, which then dissociates. Roughly twenty percent binds to haemoglobin and only about ten percent remains dissolved. The same system is what ties breathing to blood pH.'),

  ('biology', 'Genetics', 'Sex-linked inheritance', 'hard', 'multiple_choice',
   null,
   'Haemophilia is X-linked recessive. A carrier mother and an unaffected father have children. What proportion of their SONS is expected to be affected?',
   '[{"id":"A","text":"All of them"},{"id":"B","text":"One quarter"},{"id":"C","text":"One half"},{"id":"D","text":"None of them"}]',
   'C', 'Sons take their single X chromosome from their mother, and half of her X chromosomes carry the allele, so half the sons are affected. Daughters also receive a normal X from their father, so none are affected although half are carriers. One quarter is the share of ALL children affected, which answers a different question than the one asked.'),

  ('biology', 'Plant physiology', 'Transport in plants', 'medium', 'multiple_choice',
   null,
   'Water rises through the xylem of a tall tree mainly because of:',
   '[{"id":"A","text":"capillary action within the vessels alone"},{"id":"B","text":"root pressure alone pushing water upward"},{"id":"C","text":"active transport carried out by xylem vessel cells"},{"id":"D","text":"transpiration pull, created by evaporation from the leaves"}]',
   'D', 'Evaporation at the leaf surface puts the water column under tension, and cohesion between water molecules transmits that pull the whole way down to the roots. Root pressure is real but far too weak to raise water tens of metres, and mature xylem vessels are dead cells with no capacity for active transport at all.'),

  ('biology', 'Microbiology', 'Viral biology', 'medium', 'multiple_choice',
   null,
   'Viruses are not classified as living organisms mainly because they:',
   '[{"id":"A","text":"cannot carry out metabolism or reproduce outside a host cell"},{"id":"B","text":"contain no genetic material of any kind"},{"id":"C","text":"are too small to be resolved by any microscope"},{"id":"D","text":"never cause disease in other organisms"}]',
   'A', 'A virus has no metabolic machinery and must take over a host cell''s ribosomes and enzymes to replicate. It does carry genetic material, either DNA or RNA, so the second option is plainly false. Electron microscopy resolves viruses perfectly well, and many are highly pathogenic.'),

  ('biology', 'Human physiology', 'Neural conduction', 'hard', 'multiple_choice',
   null,
   'During repolarisation of a neuronal action potential, the dominant ion movement is:',
   '[{"id":"A","text":"sodium moving into the cell"},{"id":"B","text":"potassium moving out of the cell"},{"id":"C","text":"calcium moving into the cell"},{"id":"D","text":"chloride moving out of the cell"}]',
   'B', 'Depolarisation is driven by sodium rushing inward; repolarisation follows once sodium channels inactivate and the slower voltage-gated potassium channels open, letting potassium leave and carrying the membrane potential back down. Those potassium channels close sluggishly, which is what overshoots into the brief hyperpolarisation after each spike.'),

  ('biology', 'Biotechnology', 'Recombinant DNA', 'medium', 'multiple_choice',
   null,
   'Restriction endonucleases are central to recombinant DNA work because they:',
   '[{"id":"A","text":"synthesise DNA from an RNA template"},{"id":"B","text":"join DNA fragments together permanently"},{"id":"C","text":"cut DNA at specific recognition sequences"},{"id":"D","text":"unwind the double helix without cutting it"}]',
   'C', 'A restriction enzyme recognises a short specific sequence and cuts there reliably, often leaving sticky ends that will pair with any fragment cut by the same enzyme. Joining those fragments is the job of ligase, and building DNA from RNA is reverse transcriptase -- three enzymes that are easy to confuse and that do quite different things.')

) as v(section, domain, skill, difficulty, question_type, stimulus, question_text, answer_choices, correct_answer, explanation)
where e.slug = 'neet-ug'
on conflict do nothing;

-- Switched on only now, with a bank behind it.
update public.exam_definitions
set status = 'available'
where slug = 'neet-ug';
